### ISSUE TITLE
how to get consumer's id? 

### ISSUE THREAD

**Issue by niklahun** [nvllsvm/consumers#1]
Hi,
Could you please help what would be the equal of multiprocessing.current_process?
When i'm trying to get current_process from the consumers they return: AttributeError: module 'consumers' has no attribute 'current_process'.

Thanks a lot and thanks for writing this magic :) 
Cheers,
Dani

**Comment by andrewrabert** [comment]
I never intended to provide that. Using `os.getpid()` served my to uniquely identify the processes.

Also, I'm glad you've found use in this library. However, I've stopped maintaining it after learning of [`concurrent.futures.ProcessPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor). It has a nicer API than multiprocessing.Pool and comes included in the Python standard library. 

Let me know if it's docs are not clear enough. I'll be happy to craft some examples.

**Comment by niklahun** [comment]
Thanks! I had been looking into this and you are absolutely right.
